import express from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import {fileURLToPath} from 'url';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express(),PORT=process.env.PORT||7860;
const DIR=fs.existsSync('/data')?'/data':path.join(__dirname,'.data'),FILE=path.join(DIR,'cupid-games.json');
app.disable('x-powered-by');app.use(express.json({limit:'1mb'}));
const clean=(v,m=500)=>String(v||'').slice(0,m).replace(/[<>]/g,''),norm=v=>clean(v,120).trim().toLowerCase().replace(/\s+/g,' '),hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex'),token=()=>crypto.randomBytes(24).toString('base64url');
function load(){try{return JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{return[]}}function save(x){fs.mkdirSync(DIR,{recursive:true});fs.writeFileSync(FILE,JSON.stringify(x,null,2))}
const reviewClean=i=>({dateRating:Math.max(1,Math.min(5,Number(i.dateRating||1))),connection:Math.max(1,Math.min(5,Number(i.connection||1))),comfort:Math.max(1,Math.min(5,Number(i.comfort||1))),fun:Math.max(1,Math.min(5,Number(i.fun||1))),repeat:Boolean(i.repeat),favoriteActivity:clean(i.favoriteActivity,120),privateNote:clean(i.privateNote,600),submittedAt:new Date().toISOString()});
function cleanGame(i={}){return{code:clean(i.code,32).toUpperCase(),playerName:clean(i.playerName,120),partnerName:clean(i.partnerName,120),dateName:clean(i.dateName||`${i.playerName||''} + ${i.partnerName||''}`),identityKey:`${norm(i.playerName)}::${norm(i.partnerName)}`,nights:Math.max(1,Math.min(3,Number(i.nights||1))),score:Number(i.score||0),hits:Number(i.hits||0),bestCombo:Number(i.bestCombo||i.best||0),unlocks:Array.isArray(i.unlocks)?i.unlocks.map(x=>clean(x,80)).slice(0,30):[],rewards:Array.isArray(i.rewards)?i.rewards.slice(0,150).map(r=>({id:clean(r.id,80),name:clean(r.name),notes:clean(r.notes),category:clean(r.category||r.tier,80),emoji:clean(r.emoji,20),points:Number(r.points||r.cost||0),night:Math.max(0,Number(r.night||0)),duration:clean(r.duration,80),traits:r.traits&&typeof r.traits==='object'?r.traits:{}})):[],participants:i.participants||null,createdAt:clean(i.createdAt,80)||new Date().toISOString()}}
function profile(gs){const picks={},cats={},ratings=[];gs.forEach(g=>{(g.rewards||[]).forEach(r=>{picks[r.name]=(picks[r.name]||0)+1;cats[r.category||'Other']=(cats[r.category||'Other']||0)+1});Object.values(g.participants||{}).forEach(p=>p.review?.dateRating&&ratings.push(p.review.dateRating))});const sp=Object.entries(picks).sort((a,b)=>b[1]-a[1]),sc=Object.entries(cats).sort((a,b)=>b[1]-a[1]);return{identityKey:gs[0]?.identityKey,playerName:gs[0]?.playerName,partnerName:gs[0]?.partnerName,plays:gs.length,totalPoints:gs.reduce((n,g)=>n+g.score,0),averagePoints:gs.length?Math.round(gs.reduce((n,g)=>n+g.score,0)/gs.length):0,favoritePick:sp[0]?.[0]||'',favoriteCategory:sc[0]?.[0]||'',averageRating:ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):'',completedReviews:ratings.length,picks:sp.map(([name,count])=>({name,count})),games:gs.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}}
function findByToken(gs,t){const h=hash(t);for(const g of gs)for(const role of ['creator','partner'])if(g.participants?.[role]?.tokenHash===h)return{g,role,p:g.participants[role]};return null}
function shared(g){const a=g.participants?.creator?.review,b=g.participants?.partner?.review;if(!a||!b)return null;const avg=k=>((Number(a[k])+Number(b[k]))/2).toFixed(1),fav=[a.favoriteActivity,b.favoriteActivity].filter(Boolean);return{dateRating:avg('dateRating'),connection:avg('connection'),comfort:avg('comfort'),fun:avg('fun'),bothWantAnother:Boolean(a.repeat&&b.repeat),favoriteActivities:[...new Set(fav)],message:Number(avg('connection'))>=4?'Cupid sees a strong connection. Keep building on what made you both feel close.':Number(avg('fun'))>=4?'Fun was your strongest shared signal. Keep the next date playful.':'You both gave Cupid useful clues for a better next date.'}}
app.get('/health',(_q,r)=>r.json({ok:true}));
app.post('/api/save-game',(q,r)=>{const game=cleanGame(q.body);if(!game.code||!game.playerName||!game.partnerName)return r.status(400).json({error:'Missing names or code'});const creatorToken=token(),partnerToken=token();game.participants={creator:{name:game.playerName,role:'creator',tokenHash:hash(creatorToken),review:null},partner:{name:game.partnerName,role:'partner',tokenHash:hash(partnerToken),review:null}};const gs=load(),ix=gs.findIndex(x=>x.code===game.code);if(ix>=0)gs[ix]=game;else gs.unshift(game);save(gs.slice(0,5000));r.json({ok:true,code:game.code,creatorReviewToken:creatorToken,partnerReviewToken:partnerToken})});
app.get('/api/review/:token',(q,r)=>{const f=findByToken(load(),q.params.token);if(!f)return r.status(404).json({error:'Private review link not found'});const s=shared(f.g);r.json({code:f.g.code,reviewerName:f.p.name,otherName:f.role==='creator'?f.g.partnerName:f.g.playerName,role:f.role,rewards:f.g.rewards,submitted:Boolean(f.p.review),review:f.p.review?{...f.p.review,privateNote:undefined}:null,bothSubmitted:Boolean(s),shared:s})});
app.post('/api/review/:token',(q,r)=>{const gs=load(),f=findByToken(gs,q.params.token);if(!f)return r.status(404).json({error:'Private review link not found'});f.p.review=reviewClean(q.body);save(gs);r.json({ok:true,bothSubmitted:Boolean(shared(f.g)),shared:shared(f.g)})});
app.get('/api/redeem',(q,r)=>{const g=load().find(x=>x.code===clean(q.query.code,32).toUpperCase());if(!g)return r.status(404).json({error:'Reward code not found'});const{identityKey,participants,...pub}=g;r.json({...pub,reviewStatus:{creator:Boolean(participants?.creator?.review),partner:Boolean(participants?.partner?.review)}})});
app.get('/api/dashboard',(q,r)=>{if(process.env.ADMIN_PIN&&q.headers['x-admin-pin']!==process.env.ADMIN_PIN)return r.status(401).json({error:'Locked'});const query=norm(q.query.q||''),all=load(),games=query?all.filter(g=>[g.code,g.playerName,g.partnerName,g.dateName].some(v=>norm(v).includes(query))):all,grouped=new Map();all.forEach(g=>{const a=grouped.get(g.identityKey)||[];a.push(g);grouped.set(g.identityKey,a)});let profiles=[...grouped.values()].map(profile);if(query)profiles=profiles.filter(p=>[p.playerName,p.partnerName,p.identityKey,...p.games.map(g=>g.code)].some(v=>norm(v).includes(query)));const counts={};games.flatMap(g=>g.rewards||[]).forEach(x=>counts[x.name]=(counts[x.name]||0)+1);r.json({games,profiles,averageScore:games.length?Math.round(games.reduce((n,g)=>n+g.score,0)/games.length):0,topReward:Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'',submittedReviews:games.reduce((n,g)=>n+Object.values(g.participants||{}).filter(p=>p.review).length,0),matchedDates:games.filter(g=>shared(g)).length})});
app.use(express.static(path.join(__dirname,'dist'),{extensions:['html']}));app.use((_q,r)=>r.sendFile(path.join(__dirname,'dist','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`Cupid running on ${PORT}`));