import express from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import {fileURLToPath} from 'url';

const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express(),PORT=process.env.PORT||7860;
const PERSISTENT_DIR='/data',DIR=process.env.DATA_DIR||(fs.existsSync(PERSISTENT_DIR)?PERSISTENT_DIR:path.join(__dirname,'.data')),FILE=path.join(DIR,'cupid-data.json');
app.disable('x-powered-by');app.use(express.json({limit:'1mb'}));
const clean=(v,m=800)=>String(v??'').slice(0,m).replace(/[<>]/g,''),norm=v=>clean(v,160).trim().toLowerCase().replace(/\s+/g,' '),hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex'),token=()=>crypto.randomBytes(24).toString('base64url'),now=()=>new Date().toISOString();
function empty(){return{version:2,games:[],sessions:[],lastWriteAt:null}}
function load(){try{const x=JSON.parse(fs.readFileSync(FILE,'utf8'));return Array.isArray(x)?{...empty(),games:x}:x?.games?{...empty(),...x}:empty()}catch{return empty()}}
function save(data){fs.mkdirSync(DIR,{recursive:true});data.lastWriteAt=now();const tmp=FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2));fs.renameSync(tmp,FILE)}
function upsertSession(data,input,status){const id=clean(input.sessionId||input.id,80);if(!id)return null;let s=data.sessions.find(x=>x.id===id);if(!s){s={id,playerName:clean(input.playerName,120),partnerName:clean(input.partnerName,120),nights:Math.max(1,Math.min(3,Number(input.nights||1))),status:status||'started',screen:'setup',round:0,score:0,startedAt:now(),lastSeenAt:now(),completedAt:null,userAgent:clean(input.userAgent,300)};data.sessions.unshift(s)}else Object.assign(s,{playerName:clean(input.playerName||s.playerName,120),partnerName:clean(input.partnerName||s.partnerName,120),nights:Number(input.nights||s.nights),status:status||input.status||s.status,screen:clean(input.screen||s.screen,40),round:Number(input.round??s.round),score:Number(input.score??s.score),lastSeenAt:now()});return s}
const reviewClean=i=>({dateRating:Math.max(1,Math.min(5,Number(i.dateRating||1))),connection:Math.max(1,Math.min(5,Number(i.connection||1))),comfort:Math.max(1,Math.min(5,Number(i.comfort||1))),fun:Math.max(1,Math.min(5,Number(i.fun||1))),repeat:Boolean(i.repeat),favoriteActivity:clean(i.favoriteActivity,160),privateNote:clean(i.privateNote,900),submittedAt:now()});
function cleanGame(i={}){return{code:clean(i.code,32).toUpperCase(),sessionId:clean(i.sessionId,80),playerName:clean(i.playerName,120),partnerName:clean(i.partnerName,120),dateName:clean(i.dateName||`${i.playerName||''} + ${i.partnerName||''}`),identityKey:`${norm(i.playerName)}::${norm(i.partnerName)}`,nights:Math.max(1,Math.min(3,Number(i.nights||1))),score:Number(i.score||0),hits:Number(i.hits||0),shots:Number(i.shots||0),accuracy:Number(i.accuracy||0),bestCombo:Number(i.bestCombo||i.best||0),rank:clean(i.rank||'C',3),bossDefeated:Boolean(i.bossDefeated),risk:clean(i.risk||'bank',20),loot:Array.isArray(i.loot)?i.loot.slice(0,30).map(x=>({id:clean(x.id,80),name:clean(x.name,120),type:clean(x.type,40),rarity:clean(x.rarity,30),emoji:clean(x.emoji,20)})):[],rewards:Array.isArray(i.rewards)?i.rewards.slice(0,180).map(r=>({id:clean(r.id,80),name:clean(r.name,160),notes:clean(r.notes),category:clean(r.category||r.tier,80),rarity:clean(r.rarity||'Common',30),emoji:clean(r.emoji,20),points:Number(r.points||r.cost||0),night:Math.max(0,Number(r.night||0)),duration:clean(r.duration,80),traits:r.traits&&typeof r.traits==='object'?r.traits:{}})):[],participants:i.participants||null,invite:i.invite||null,createdAt:clean(i.createdAt,80)||now()}}
function findByToken(games,t,kind='review'){const h=hash(t);for(const g of games){if(kind==='invite'&&g.invite?.tokenHash===h)return{g};for(const role of ['creator','partner'])if(g.participants?.[role]?.tokenHash===h)return{g,role,p:g.participants[role]}}return null}
function shared(g){const a=g.participants?.creator?.review,b=g.participants?.partner?.review;if(!a||!b)return null;const avg=k=>Number(((Number(a[k])+Number(b[k]))/2).toFixed(1)),favorites=[a.favoriteActivity,b.favoriteActivity].filter(Boolean);let message='Cupid has enough clues to make the next run even better.';if(avg('connection')>=4.5)message='Strong connection unlocked. Keep choosing moments that give you room to talk and laugh.';else if(avg('fun')>=4.5)message='Playfulness is your strongest shared signal. Your next date should keep the energy moving.';else if(avg('comfort')>=4.5)message='You both felt comfortable—an excellent foundation for a bolder next adventure.';return{dateRating:avg('dateRating'),connection:avg('connection'),comfort:avg('comfort'),fun:avg('fun'),bothWantAnother:Boolean(a.repeat&&b.repeat),favoriteActivities:[...new Set(favorites)],message}}
function profile(gs){const picks={},cats={},ratings=[];gs.forEach(g=>{(g.rewards||[]).forEach(r=>{picks[r.name]=(picks[r.name]||0)+1;cats[r.category||'Other']=(cats[r.category||'Other']||0)+1});Object.values(g.participants||{}).forEach(p=>p.review?.dateRating&&ratings.push(p.review.dateRating))});const sp=Object.entries(picks).sort((a,b)=>b[1]-a[1]),sc=Object.entries(cats).sort((a,b)=>b[1]-a[1]);return{identityKey:gs[0]?.identityKey,playerName:gs[0]?.playerName,partnerName:gs[0]?.partnerName,plays:gs.length,totalPoints:gs.reduce((n,g)=>n+g.score,0),averagePoints:gs.length?Math.round(gs.reduce((n,g)=>n+g.score,0)/gs.length):0,favoritePick:sp[0]?.[0]||'',favoriteCategory:sc[0]?.[0]||'',averageRating:ratings.length?(ratings.reduce((a,b)=>a+b,0)/ratings.length).toFixed(1):'',completedReviews:ratings.length,picks:sp.map(([name,count])=>({name,count})),games:gs.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}}
app.get('/health',(_q,r)=>{const d=load();r.json({ok:true,storage:{dir:DIR,persistent:DIR===PERSISTENT_DIR,games:d.games.length,sessions:d.sessions.length,lastWriteAt:d.lastWriteAt}})});
app.post('/api/session/start',(q,r)=>{const d=load(),s=upsertSession(d,{...q.body,userAgent:q.headers['user-agent']},'started');if(!s)return r.status(400).json({error:'Missing session id'});save(d);r.json({ok:true,session:s})});
app.post('/api/session/progress',(q,r)=>{const d=load(),s=upsertSession(d,q.body,q.body.status||'playing');if(!s)return r.status(400).json({error:'Missing session id'});save(d);r.json({ok:true})});
app.post('/api/save-game',(q,r)=>{const game=cleanGame(q.body);if(!game.code||!game.playerName||!game.partnerName)return r.status(400).json({error:'Missing names or code'});const creatorToken=token(),partnerToken=token(),inviteToken=token();game.participants={creator:{name:game.playerName,role:'creator',tokenHash:hash(creatorToken),review:null},partner:{name:game.partnerName,role:'partner',tokenHash:hash(partnerToken),review:null}};game.invite={tokenHash:hash(inviteToken),openedAt:null,acceptedAt:null};const d=load(),ix=d.games.findIndex(x=>x.code===game.code);if(ix>=0)d.games[ix]=game;else d.games.unshift(game);const s=upsertSession(d,{sessionId:game.sessionId,playerName:game.playerName,partnerName:game.partnerName,nights:game.nights,screen:'finale',score:game.score},'completed');if(s)s.completedAt=now();d.games=d.games.slice(0,5000);d.sessions=d.sessions.slice(0,10000);save(d);r.json({ok:true,code:game.code,creatorReviewToken:creatorToken,partnerReviewToken:partnerToken,inviteToken})});
app.get('/api/invite/:token',(q,r)=>{const d=load(),f=findByToken(d.games,q.params.token,'invite');if(!f)return r.status(404).json({error:'Invite not found'});if(!f.g.invite.openedAt){f.g.invite.openedAt=now();save(d)}const{participants,identityKey,invite,...pub}=f.g;r.json({...pub,inviteStatus:{opened:Boolean(f.g.invite.openedAt),accepted:Boolean(f.g.invite.acceptedAt)}})});
app.post('/api/invite/:token/accept',(q,r)=>{const d=load(),f=findByToken(d.games,q.params.token,'invite');if(!f)return r.status(404).json({error:'Invite not found'});f.g.invite.acceptedAt=now();save(d);r.json({ok:true,acceptedAt:f.g.invite.acceptedAt})});
app.get('/api/review/:token',(q,r)=>{const f=findByToken(load().games,q.params.token);if(!f)return r.status(404).json({error:'Private review link not found'});const s=shared(f.g);r.json({code:f.g.code,reviewerName:f.p.name,otherName:f.role==='creator'?f.g.partnerName:f.g.playerName,role:f.role,rewards:f.g.rewards,submitted:Boolean(f.p.review),review:f.p.review?{...f.p.review,privateNote:undefined}:null,bothSubmitted:Boolean(s),shared:s})});
app.post('/api/review/:token',(q,r)=>{const d=load(),f=findByToken(d.games,q.params.token);if(!f)return r.status(404).json({error:'Private review link not found'});f.p.review=reviewClean(q.body);save(d);r.json({ok:true,bothSubmitted:Boolean(shared(f.g)),shared:shared(f.g)})});
app.get('/api/redeem',(q,r)=>{const g=load().games.find(x=>x.code===clean(q.query.code,32).toUpperCase());if(!g)return r.status(404).json({error:'Reward code not found'});const{identityKey,participants,invite,...pub}=g;r.json({...pub,reviewStatus:{creator:Boolean(participants?.creator?.review),partner:Boolean(participants?.partner?.review)},inviteStatus:{opened:Boolean(invite?.openedAt),accepted:Boolean(invite?.acceptedAt)}})});
app.get('/api/dashboard',(q,r)=>{if(process.env.ADMIN_PIN&&q.headers['x-admin-pin']!==process.env.ADMIN_PIN)return r.status(401).json({error:'Locked'});const query=norm(q.query.q||''),d=load(),all=d.games,games=query?all.filter(g=>[g.code,g.playerName,g.partnerName,g.dateName].some(v=>norm(v).includes(query))):all,sessions=query?d.sessions.filter(s=>[s.id,s.playerName,s.partnerName,s.status].some(v=>norm(v).includes(query))):d.sessions,grouped=new Map();all.forEach(g=>{const a=grouped.get(g.identityKey)||[];a.push(g);grouped.set(g.identityKey,a)});let profiles=[...grouped.values()].map(profile);if(query)profiles=profiles.filter(p=>[p.playerName,p.partnerName,p.identityKey,...p.games.map(g=>g.code)].some(v=>norm(v).includes(query)));const thirty=Date.now()-30*60*1000,abandoned=sessions.filter(s=>s.status!=='completed'&&new Date(s.lastSeenAt).getTime()<thirty).length;r.json({games,sessions,profiles,storage:{dir:DIR,persistent:DIR===PERSISTENT_DIR,lastWriteAt:d.lastWriteAt},metrics:{started:sessions.length,playing:sessions.filter(s=>s.status==='playing').length,completed:games.length,abandoned,inviteOpened:games.filter(g=>g.invite?.openedAt).length,inviteAccepted:games.filter(g=>g.invite?.acceptedAt).length,submittedReviews:games.reduce((n,g)=>n+Object.values(g.participants||{}).filter(p=>p.review).length,0),matchedDates:games.filter(g=>shared(g)).length}})});
app.use(express.static(path.join(__dirname,'dist'),{extensions:['html']}));app.use((_q,r)=>r.sendFile(path.join(__dirname,'dist','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`Cupid running on ${PORT}; storage=${DIR}`));