import { useMemo, useState } from 'react';

const rewards = {
  common: { label: 'Common', emoji: '❤️', points: 80, items: ['Coffee Date','Ice Cream','Walk the Pier','Visit Vinoy Park','Sunset Walk','Browse Local Shops','Bookstore Date'] },
  rare: { label: 'Rare', emoji: '💙', points: 150, items: ['Mural Tour','Dali Museum','Chihuly Collection','DJ Set','Live Blues Music','Wine Bar','Craft Brewery','Dessert Crawl','Rooftop Cocktails'] },
  epic: { label: 'Chemistry', emoji: '💜', points: 250, items: ['Massage','First Base','Second Base','Third Base','Home Run','Your FANTASY','Cook Dinner Together','Dance in the Living Room','Movie Night','Candlelit Dessert','Watch the Sunrise','No Phones for One Hour'] },
  legendary: { label: 'Legendary', emoji: '💛', points: 500, items: ['Golden Arrow','Choose Any Reward','Unlock Three Cards','Double Reward','Skip Next Miss','Weekend Jackpot'] }
};
const cards = ["What's your biggest green flag?","What's your biggest red flag?","What's your love language?","What's your ideal Saturday together?","What makes you feel appreciated?","If we traveled anywhere tomorrow, where would we go?","What does a perfect morning together look like?","What's something you've always wanted to try on a date?"];
const stages = ['Strangers','Curious','Comfortable','Flirting','Chemistry','Spark','Electric','Unforgettable Weekend'];

function code() { const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; return Array.from({length:7},()=>a[Math.floor(Math.random()*a.length)]).join(''); }
function draw(round) { const x=Math.random(); let r='common'; if(round%10===0||x>.96) r='legendary'; else if(x>.70) r='epic'; else if(x>.38) r='rare'; const tier=rewards[r]; const name=tier.items[Math.floor(Math.random()*tier.items.length)]; return { id: crypto.randomUUID?.() || String(Date.now()+Math.random()), name, rarity:r, tier:tier.label, emoji:tier.emoji, points:tier.points, createdAt:new Date().toISOString() }; }

function Dashboard(){
  const [pin,setPin]=useState(''); const [data,setData]=useState(null); const [err,setErr]=useState('');
  async function load(){ setErr(''); try{ const res=await fetch('/api/dashboard',{headers:{'x-admin-pin':pin}}); if(!res.ok) throw new Error(); setData(await res.json()); }catch{ setErr('Locked or no data yet.'); } }
  function csv(){ if(!data?.games?.length) return; const rows=[['date','player','partner','code','score','winnings'],...data.games.map(g=>[g.createdAt,g.playerName,g.partnerName,g.code,g.score,(g.rewards||[]).map(r=>r.customText||r.name).join('|')])]; const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='cupids-revenge-results.csv'; a.click(); URL.revokeObjectURL(url); }
  return <main className="page"><section className="panel"><p className="eyebrow">Private Admin</p><h1>Cupid Dashboard</h1><p>No public leaderboard. Only private game results.</p><div className="row"><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Admin PIN"/><button onClick={load}>Unlock</button></div>{err&&<p className="error">{err}</p>}</section>{data&&<section className="panel wide"><div className="top"><h2>Results</h2><button onClick={csv}>Export CSV</button></div><div className="metrics"><b>{data.games.length}<span>Games</span></b><b>{data.totalRewards}<span>Rewards</span></b><b>{data.averageScore}<span>Avg Score</span></b><b>{data.topReward||'—'}<span>Top Reward</span></b></div><table><thead><tr><th>Date</th><th>Players</th><th>Code</th><th>Score</th><th>Winnings</th></tr></thead><tbody>{data.games.map(g=><tr key={g.code}><td>{new Date(g.createdAt).toLocaleString()}</td><td>{g.playerName} / {g.partnerName}</td><td>{g.code}</td><td>{g.score}</td><td>{(g.rewards||[]).map(r=>r.customText||r.name).join(', ')}</td></tr>)}</tbody></table></section>}</main>;
}
function Redeem(){ const c=location.pathname.split('/').pop(); const [game,setGame]=useState(null); const [err,setErr]=useState(''); useState(()=>{ fetch('/api/redeem?code='+encodeURIComponent(c)).then(r=>r.ok?r.json():Promise.reject()).then(setGame).catch(()=>setErr('Reward code not found.')); }); return <main className="page"><section className="panel wide"><p className="eyebrow">Reward Wallet</p>{err&&<h1>{err}</h1>}{game&&<><h1>{game.playerName} & {game.partnerName}</h1><p>Code <b>{game.code}</b> · Score {game.score}</p><div className="wallet">{game.rewards.map(r=><div className={'chip '+r.rarity} key={r.id}><span>{r.emoji}</span><b>{r.customText||r.name}</b><em>{r.points}</em></div>)}</div><p className="fine">Cash these in together. Consent, comfort, and timing always win.</p></>}</section></main>; }

export default function App(){
  if(location.pathname==='/dashboard') return <Dashboard/>;
  if(location.pathname.startsWith('/redeem/')) return <Redeem/>;
  const [started,setStarted]=useState(false); const [form,setForm]=useState({playerName:'',partnerName:''}); const [game,setGame]=useState({hits:0,misses:0,score:0,rewards:[],round:1}); const [modal,setModal]=useState(null); const [saved,setSaved]=useState(null); const [fantasy,setFantasy]=useState('');
  const pct=Math.min(100,game.rewards.length*12.5); const stage=stages[Math.min(stages.length-1,Math.floor(pct/100*stages.length))]; const ready=useMemo(()=>form.playerName.trim()&&form.partnerName.trim(),[form]);
  function shoot(hit){ if(!hit){ setGame(g=>({...g,misses:g.misses+1,round:g.round+1})); return; } const r=draw(game.round); const card=Math.random()>.5?cards[Math.floor(Math.random()*cards.length)]:''; setGame(g=>({...g,hits:g.hits+1,round:g.round+1,score:g.score+r.points,rewards:[...g.rewards,r]})); setModal({reward:r,card}); }
  async function finish(){ const payload={...game,...form,code:code(),createdAt:new Date().toISOString()}; await fetch('/api/save-game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}).catch(()=>{}); setSaved(payload); }
  if(saved) return <main className="page"><section className="panel victory"><h1>You defeated Cupid...</h1><p>by creating your own love story.</p><b className="bigcode">{saved.code}</b><p>Open <b>/redeem/{saved.code}</b> to cash in rewards.</p><button onClick={()=>location.href='/redeem/'+saved.code}>Open Reward Wallet</button></section></main>;
  return <main className="app"><div className="glow g1"/><div className="glow g2"/>{!started?<section className="panel hero"><div className="logo">💘</div><p className="eyebrow">Cupid's Revenge</p><h1>Shoot Cupid. Unlock the Perfect Weekend.</h1><p>Cupid has been interfering with love for centuries. Tonight, it is your turn.</p><div className="names"><input value={form.playerName} onChange={e=>setForm({...form,playerName:e.target.value})} placeholder="Player One"/><input value={form.partnerName} onChange={e=>setForm({...form,partnerName:e.target.value})} placeholder="Player Two"/></div><button disabled={!ready} onClick={()=>setStarted(true)}>Start Our Adventure</button><p className="fine">Private results only. No visible leaderboards.</p></section>:<><header><div><p className="eyebrow">Cupid's Revenge</p><h2>{form.playerName} + {form.partnerName}</h2></div><button onClick={finish} disabled={!game.rewards.length}>Finish + Save</button></header><section className="layout"><div className="arena"><div className="skyline">🌴 🌇 🌊</div><button className="cupid" onClick={()=>shoot(true)}>💘<span>Hit Cupid</span></button><button className="miss" onClick={()=>shoot(false)}>Miss Shot</button><p>Tap Cupid to shoot. Misses make him faster. Every hit unlocks a weekend reward.</p></div><aside className="panel side"><div className="stat"><span>Hits</span><b>{game.hits}</b></div><div className="stat"><span>Misses</span><b>{game.misses}</b></div><div className="stat"><span>Score</span><b>{game.score}</b></div><div className="meterlabel"><span>{stage}</span><span>{Math.round(pct)}%</span></div><div className="meter"><i style={{width:pct+'%'}}/></div><h3>Weekend Wallet</h3><div className="wallet">{game.rewards.slice().reverse().map(r=><div className={'chip '+r.rarity} key={r.id}><span>{r.emoji}</span><b>{r.customText||r.name}</b><em>{r.points}</em></div>)}</div></aside></section></>}{modal&&<div className="modal"><section className={'panel reward '+modal.reward.rarity}><div className="badge">{modal.reward.emoji}</div><p className="eyebrow">{modal.reward.tier} unlocked</p><h2>{modal.reward.name}</h2><p>This card is now in your private weekend wallet.</p>{modal.reward.name==='Your FANTASY'&&<textarea value={fantasy} onChange={e=>setFantasy(e.target.value)} placeholder="Write a playful, consensual idea you both agree sounds fun..."/>}{modal.card&&<div className="connection"><b>Connection Card</b><span>{modal.card}</span></div>}<button onClick={()=>{ if(modal.reward.name==='Your FANTASY'&&fantasy.trim()){ setGame(g=>({...g,rewards:g.rewards.map(r=>r.id===modal.reward.id?{...r,customText:fantasy}:r)})); } setFantasy(''); setModal(null); }}>Add to Weekend</button></section></div>}</main>;
}
