import {useEffect,useMemo,useRef,useState} from 'react';

const BUDGET=1200;
const MAP=[
 {name:'Heart Harbor',icon:'💗',seconds:13,help:'Build a combo before the harbor closes.'},
 {name:'Broken Boulevard',icon:'💔',seconds:14,help:'Broken hearts need two clean hits.'},
 {name:'Letter Lagoon',icon:'💌',seconds:14,help:'Catch love letters and avoid black hearts.'},
 {name:"Cupid's Tower",icon:'💘',seconds:22,help:'Defeat Cupid before he escapes.'}
];
const POWERUPS={
 slow:{id:'slow',name:'Slow Time',emoji:'⏳',type:'power',rarity:'Rare',text:'+5 seconds next stage'},
 double:{id:'double',name:'Double Love',emoji:'✨',type:'power',rarity:'Epic',text:'2× points next stage'},
 shield:{id:'shield',name:'Heart Shield',emoji:'🛡️',type:'power',rarity:'Rare',text:'Blocks one black heart'}
};
const CARD_ROWS=[
 ['coffee','Coffee Date','Food',120,'☕','45 min','Common'],['icecream','Ice Cream','Food',140,'🍦','45 min','Common'],['pier','St. Pete Pier Walk','Adventure',180,'🌊','60 min','Common'],['sunset','Sunset Walk','Romance',180,'🌅','60 min','Rare'],['nophones','No Phones Hour','Connection',180,'📵','60 min','Rare'],['dance','Slow Dance','Romance',220,'💃','30 min','Rare'],['loveletter','Write Love Letters','Connection',220,'💌','45 min','Epic'],['minigolf','Mini Golf','Adventure',240,'⛳','90 min','Common'],['movie','Movie Night','Romance',240,'🎬','2 hrs','Common'],['first','First Base','Chemistry',250,'😘','Your pace','Rare'],['picnic','Waterfront Picnic','Food',260,'🧺','90 min','Rare'],['murals','Mural Tour','Adventure',260,'🖼️','90 min','Rare'],['cocktails','Rooftop Cocktails','Food',280,'🍸','90 min','Epic'],['sunrise','Watch the Sunrise','Romance',300,'🌄','90 min','Epic'],['massage','Massage','Romance',340,'💆','45 min','Epic'],['dinner','Dinner Downtown','Food',360,'🍽️','2 hrs','Rare'],['chihuly','Chihuly Collection','Adventure',380,'✨','90 min','Epic'],['dali','Dali Museum','Adventure',420,'🎨','2 hrs','Epic'],['second','Second Base','Chemistry',420,'💋','Your pace','Epic'],['kayak','Sunset Kayak','Adventure',480,'🛶','2 hrs','Legendary'],['third','Third Base','Chemistry',620,'🔥','Your pace','Legendary'],['homerun','Home Run','Chemistry',900,'❤️‍🔥','Your pace','Legendary'],['fantasy','Your Fantasy','Chemistry',1000,'🌶️','Your pace','Secret']
];
const CARDS=CARD_ROWS.map(([id,name,category,cost,emoji,duration,rarity])=>({id,name,category,cost,emoji,duration,rarity,traits:{romance:category==='Romance'?5:2,fun:category==='Adventure'?5:3,connection:category==='Connection'?5:2,chemistry:category==='Chemistry'?5:1}}));
const POINTS={heart:90,gold:210,letter:150,broken:170,bomb:-140,cupid:280,decoy:-110};
const ICON={heart:'💗',gold:'💛',letter:'💌',broken:'💔',bomb:'🖤',cupid:'💘',decoy:'😈'};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const code=()=>Array.from({length:7},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
function loadProfile(){try{return JSON.parse(localStorage.getItem('cupid-v5'))||{collection:{},custom:[],picks:{}}}catch{return{collection:{},custom:[],picks:{}}}}
function saveProfile(x){localStorage.setItem('cupid-v5',JSON.stringify(x))}
const audio={ctx:null,timer:null,on:false,step:0,listeners:new Set(),notify(){this.listeners.forEach(f=>f(this.on))},async toggle(){if(this.on){clearInterval(this.timer);this.timer=null;this.on=false;this.notify();return}const A=window.AudioContext||window.webkitAudioContext;if(!A)throw new Error('unsupported');this.ctx=this.ctx||new A();await this.ctx.resume();const beat=()=>{const c=this.ctx,o=c.createOscillator(),g=c.createGain(),f=c.createBiquadFilter(),seq=[110,165,220,247,294,247,196,147];o.type='sawtooth';o.frequency.value=seq[this.step++%seq.length];f.type='lowpass';f.frequency.value=760;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.045,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.23);o.connect(f).connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.25)};beat();this.timer=setInterval(beat,270);this.on=true;this.notify()}};
function Sound(){const[on,setOn]=useState(audio.on),[error,setError]=useState('');useEffect(()=>{audio.listeners.add(setOn);return()=>audio.listeners.delete(setOn)},[]);return <button className="cv5-sound" onClick={async()=>{try{await audio.toggle();setError('')}catch{setError('Tap again')}}}>{on?'🔊':'🔇'}<span>{on?'Neon Run':'Music'}</span>{error&&<small>{error}</small>}</button>}
function City(){return <div className="cv5-city" aria-hidden="true"><div className="cv5-stars"/><div className="cv5-orb"/><div className="cv5-cloud a"/><div className="cv5-cloud b"/><div className="cv5-skyline"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="cv5-water"><i/><i/><i/></div><div className="cv5-palm left">🌴</div><div className="cv5-palm right">🌴</div></div>}
function Map({round,screen}){return <div className="cv5-map">{MAP.map((x,i)=><div key={x.name} className={`${i<round?'done':''} ${i===round?'active':''} ${i>round?'locked':''}`}><span>{x.icon}</span><b>{x.name}</b><small>{i<round?'Cleared':i===round&&screen==='game'?'Playing':i===round?'Next':'Locked'}</small>{i<MAP.length-1&&<i/>}</div>)}</div>}
function makeTarget(round,id,bossHp=8){if(round===3){const r=Math.random();const type=r>.64?'decoy':r>.42?'bomb':'cupid';return{id,type,x:6+Math.random()*78,y:15+Math.random()*58,hp:type==='cupid'?bossHp:1,phase:bossHp<=3?3:bossHp<=6?2:1}}const r=Math.random();let type='heart';if(r>.92)type='bomb';else if(r>.79)type='gold';else if(round===2&&r>.43)type='letter';else if(round===1&&r>.4)type='broken';return{id,type,x:6+Math.random()*80,y:12+Math.random()*64,hp:type==='broken'?2:1}}
function rankRun(score,goal,accuracy,best,boss){if(!boss)return'C';const ratio=score/Math.max(goal,1);if(ratio>=1.65&&accuracy>=.78&&best>=14)return'S';if(ratio>=1.35&&accuracy>=.65)return'A';if(ratio>=1.1)return'B';return'C'}
function rarityClass(r='Common'){return r.toLowerCase()}
function draftOptions(round){const card=CARDS[(round*5+Math.floor(Math.random()*CARDS.length))%CARDS.length];const powers=round%2?[POWERUPS.double,POWERUPS.shield]:[POWERUPS.slow,POWERUPS.double];return[Math.random()>.5?{...card,type:'card',text:'Adds this date card to your permanent collection'}:powers[0],powers[1],{...card,type:'card',text:'Collect this card and receive 50% off this run'}]}
function shareNative(title,text,url){if(navigator.share)return navigator.share({title,text,url});return navigator.clipboard.writeText(url).then(()=>alert('Link copied.'))}

function Setup({form,setForm,start}){const[step,setStep]=useState(0),valid=step===0?form.playerName.trim():step===1?form.partnerName.trim():true;return <main className="cv5-screen cv5-setup"><City/><Sound/><button className="cv5-admin-link" onClick={()=>location.href='/dashboard'}>Admin</button><section className="cv5-glass cv5-setup-card"><div className="cv5-logo">💘</div><p className="cv5-kicker">Cupid's Revenge · St. Pete</p><h1>{step===0?'Who is entering the city?':step===1?'Who are you earning the date for?':'Choose your run length'}</h1>{step<2?<input autoFocus value={step===0?form.playerName:form.partnerName} onChange={e=>setForm({...form,[step===0?'playerName':'partnerName']:e.target.value})} placeholder={step===0?'Your name':'Their name'} onKeyDown={e=>e.key==='Enter'&&valid&&setStep(step+1)}/>:<div className="cv5-night-picks">{[1,2,3].map(n=><button key={n} className={form.nights===n?'active':''} onClick={()=>setForm({...form,nights:n})}><b>{n}</b><span>Night{n>1?'s':''}</span><small>{n*BUDGET} Love Points</small></button>)}</div>}<div className="cv5-actions">{step>0&&<button className="ghost" onClick={()=>setStep(step-1)}>Back</button>}<button disabled={!valid} onClick={()=>step<2?setStep(step+1):start()}>{step<2?'Continue':'Enter St. Pete'}</button></div></section></main>}

function Review(){const token=location.pathname.split('/').pop(),[data,setData]=useState(),[form,setForm]=useState({dateRating:5,connection:5,comfort:5,fun:5,repeat:true,favoriteActivity:'',privateNote:''}),[saved,setSaved]=useState(false),[error,setError]=useState('');useEffect(()=>{fetch('/api/review/'+token).then(r=>r.ok?r.json():Promise.reject()).then(x=>{setData(x);if(x.review)setForm(f=>({...f,...x.review}))}).catch(()=>setError('This private review link is invalid.'))},[token]);const score=(key,label)=><label><b>{label}</b><div className="cv5-rating">{[1,2,3,4,5].map(n=><button key={n} className={form[key]===n?'active':''} onClick={()=>setForm({...form,[key]:n})}>{n}</button>)}</div></label>;async function submit(){const r=await fetch('/api/review/'+token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});if(r.ok){const x=await r.json();setSaved(true);setData(v=>({...v,submitted:true,bothSubmitted:x.bothSubmitted,shared:x.shared}))}}return <main className="cv5-screen cv5-review"><City/><section className="cv5-glass cv5-review-card">{error?<h1>{error}</h1>:data&&<><p className="cv5-kicker">Private review for {data.reviewerName}</p><h1>How was your date with {data.otherName}?</h1>{data.bothSubmitted&&data.shared?<Shared shared={data.shared}/>:saved||data.submitted?<div className="cv5-wait"><h2>Review saved.</h2><p>Cupid is waiting for the other private review. Raw answers stay private.</p></div>:<div className="cv5-review-form">{score('dateRating','Overall date')}{score('connection','Connection')}{score('comfort','Comfort')}{score('fun','Fun')}<label><b>Favorite date card</b><select value={form.favoriteActivity} onChange={e=>setForm({...form,favoriteActivity:e.target.value})}><option value="">Choose one</option>{data.rewards.map(x=><option key={x.id+x.night} value={x.name}>{x.emoji} {x.name}</option>)}</select></label><label className="cv5-check"><input type="checkbox" checked={form.repeat} onChange={e=>setForm({...form,repeat:e.target.checked})}/> I want another date together</label><textarea value={form.privateNote} onChange={e=>setForm({...form,privateNote:e.target.value})} placeholder="Private note for Cupid"/><button onClick={submit}>Submit Private Review</button></div>}</>}</section></main>}
function Shared({shared}){return <div className="cv5-shared"><p className="cv5-kicker">Both reviews complete</p><h2>Cupid Match Unlocked</h2><div>{['dateRating','connection','comfort','fun'].map(k=><b key={k}>{shared[k]}<span>{k==='dateRating'?'Date':k}</span></b>)}</div><p>{shared.message}</p></div>}
function Invite(){const token=location.pathname.split('/').pop(),[game,setGame]=useState(),[accepted,setAccepted]=useState(false),[error,setError]=useState('');useEffect(()=>{fetch('/api/invite/'+token).then(r=>r.ok?r.json():Promise.reject()).then(x=>{setGame(x);setAccepted(x.inviteStatus.accepted)}).catch(()=>setError('This date invitation is unavailable.'))},[token]);async function accept(){const r=await fetch('/api/invite/'+token+'/accept',{method:'POST'});if(r.ok)setAccepted(true)}return <main className="cv5-screen cv5-invite"><City/><section className="cv5-glass cv5-invite-card">{error?<h1>{error}</h1>:game&&<><p className="cv5-kicker">A date invitation from {game.playerName}</p><h1>{game.partnerName}, Cupid built this for you.</h1><div className={`cv5-rank rank-${game.rank}`}>{game.rank}</div><p>{game.nights} night{game.nights>1?'s':''} · {game.rewards.length} date cards</p>{accepted?<div className="cv5-accepted">💘 You're in. Cupid told {game.playerName}.</div>:<button onClick={accept}>I'm In</button>}<button className="ghost" onClick={()=>location.href='/redeem/'+game.code}>View the Date</button></>}</section></main>}
function Redeem(){const c=location.pathname.split('/').pop(),[g,setG]=useState();useEffect(()=>{fetch('/api/redeem?code='+c).then(r=>r.ok?r.json():null).then(setG)},[c]);return <main className="cv5-screen cv5-redeem"><City/><section className="cv5-glass cv5-itinerary">{g&&<><p className="cv5-kicker">Cupid itinerary</p><h1>{g.playerName} & {g.partnerName}</h1><div className={`cv5-rank rank-${g.rank}`}>{g.rank}</div><b className="cv5-code">{g.code}</b>{Array.from({length:g.nights},(_,night)=><div className="cv5-timeline" key={night}><h2>Night {night+1}</h2>{g.rewards.filter(x=>x.night===night).map((x,i)=><article key={x.id+i} className={rarityClass(x.rarity)}><span>{x.emoji}</span><div><b>{x.name}</b><small>{x.rarity} · {x.duration}</small>{x.notes&&<p>{x.notes}</p>}</div></article>)}</div>)}</>}</section></main>}
function Dashboard(){const[pin,setPin]=useState(''),[q,setQ]=useState(''),[data,setData]=useState(),[selected,setSelected]=useState(),[error,setError]=useState('');async function load(){setError('');const r=await fetch('/api/dashboard?q='+encodeURIComponent(q),{headers:{'x-admin-pin':pin}});if(!r.ok)return setError('Incorrect PIN or dashboard unavailable.');const x=await r.json();setData(x);setSelected(x.profiles?.[0])}return <main className="cv5-admin"><header><p className="cv5-kicker">Private operations</p><h1>Cupid Admin</h1><div className="cv5-admin-search"><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Admin PIN"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, session, or confirmation"/><button onClick={load}>Load</button></div>{error&&<p>{error}</p>}</header>{data&&<><div className={`cv5-storage ${data.storage.persistent?'ok':'warning'}`}><b>{data.storage.persistent?'Durable storage active':'Storage warning'}</b><span>{data.storage.persistent?'Player history is writing to /data.':'This Space is using temporary container storage. History can disappear after rebuilds. Enable Hugging Face persistent storage or set DATA_DIR to a durable volume.'}</span></div><section className="cv5-admin-metrics">{Object.entries(data.metrics).map(([k,v])=><article key={k}><b>{v}</b><span>{k.replace(/([A-Z])/g,' $1')}</span></article>)}</section><section className="cv5-funnel"><h2>Recent player sessions</h2>{data.sessions.slice(0,30).map(s=><article key={s.id}><div><b>{s.playerName||'Unnamed'} + {s.partnerName||'Unknown'}</b><small>{s.id} · {new Date(s.lastSeenAt).toLocaleString()}</small></div><em className={'status-'+s.status}>{s.status}</em><span>Round {Number(s.round)+1} · {s.score} pts · {s.screen}</span></article>)}</section><section className="cv5-admin-grid"><aside>{data.profiles.map(p=><button key={p.identityKey} className={selected?.identityKey===p.identityKey?'active':''} onClick={()=>setSelected(p)}><b>{p.playerName} + {p.partnerName}</b><small>{p.plays} completed runs · {p.completedReviews} reviews</small></button>)}</aside>{selected&&<article className="cv5-profile"><h2>{selected.playerName} + {selected.partnerName}</h2><p>{selected.favoriteCategory||'No category yet'} · {selected.favoritePick||'No pick yet'} · {selected.averageRating||'No rating'}★</p>{selected.games.map(g=><div className="cv5-history" key={g.code}><b>{g.rank} Rank · {g.code} · {g.score} pts</b><small>Invite: {g.invite?.acceptedAt?'accepted':g.invite?.openedAt?'opened':'not opened'} · Reviews: {Object.values(g.participants||{}).filter(x=>x.review).length}/2</small><p>{g.rewards.map(x=>x.name).join(' → ')}</p></div>)}</article>}</section></>}</main>}

export default function CupidV5(){
 if(location.pathname==='/dashboard')return <Dashboard/>;
 if(location.pathname.startsWith('/review/'))return <Review/>;
 if(location.pathname.startsWith('/invite/'))return <Invite/>;
 if(location.pathname.startsWith('/redeem/'))return <Redeem/>;
 const[screen,setScreen]=useState('setup'),[form,setForm]=useState({playerName:'',partnerName:'',nights:1}),[sessionId]=useState(uid),[round,setRound]=useState(0),[time,setTime]=useState(MAP[0].seconds),[targets,setTargets]=useState([]),[game,setGame]=useState({score:0,hits:0,shots:0,combo:0,best:0}),[bossHp,setBossHp]=useState(8),[bossDefeated,setBossDefeated]=useState(false),[mods,setMods]=useState({slow:0,double:0,shield:0}),[activeMods,setActiveMods]=useState({slow:false,double:false,shield:false}),[loot,setLoot]=useState([]),[draft,setDraft]=useState([]),[risk,setRisk]=useState('bank'),[stake,setStake]=useState(0),[profile,setProfile]=useState(loadProfile),[discounts,setDiscounts]=useState({}),[plans,setPlans]=useState([[],[],[]]),[night,setNight]=useState(0),[custom,setCustom]=useState({name:'',emoji:'✨',duration:'Your plan',notes:''}),[showCustom,setShowCustom]=useState(false),[saved,setSaved]=useState(),[links,setLinks]=useState();
 const ids=useRef(1),goal=form.nights*BUDGET,allCards=useMemo(()=>[...CARDS,...profile.custom].sort((a,b)=>(profile.collection?.[b.id]||0)-(profile.collection?.[a.id]||0)||a.cost-b.cost),[profile]),spent=plans[night].reduce((n,x)=>n+x.finalCost,0),left=BUDGET-spent,totalSpent=plans.flat().reduce((n,x)=>n+x.finalCost,0),wallet=game.score-totalSpent,accuracy=game.shots?game.hits/game.shots:1,rank=rankRun(game.score,goal,accuracy,game.best,bossDefeated);
 function progress(status,extra={}){fetch('/api/session/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId,playerName:form.playerName,partnerName:form.partnerName,nights:form.nights,status,screen,round,score:game.score,...extra})}).catch(()=>{})}
 async function start(){await fetch('/api/session/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId,...form})}).catch(()=>{});setRound(0);setGame({score:0,hits:0,shots:0,combo:0,best:0});setBossHp(8);setBossDefeated(false);setLoot([]);setPlans([[],[],[]]);setNight(0);beginRound(0)}
 function beginRound(next){const activated={slow:mods.slow>0,double:mods.double>0,shield:mods.shield>0};setActiveMods(activated);setMods({slow:Math.max(0,mods.slow-1),double:Math.max(0,mods.double-1),shield:Math.max(0,mods.shield-1)});setRound(next);setTime(MAP[next].seconds+(activated.slow?5:0));setTargets([]);setScreen('game');progress('playing',{screen:'game',round:next})}
 useEffect(()=>{if(screen!=='game')return;setTargets(Array.from({length:round===3?4:7},()=>makeTarget(round,ids.current++,bossHp)));const interval=setInterval(()=>setTargets(t=>{if(round===3){const kept=t.filter(x=>x.type==='cupid').slice(0,1);return[...kept,...Array.from({length:3},()=>makeTarget(round,ids.current++,bossHp))]}return t.length>11?t:[...t,makeTarget(round,ids.current++,bossHp)]}),round===3?760:360);return()=>clearInterval(interval)},[screen,round,bossHp]);
 useEffect(()=>{if(screen!=='game')return;const timer=setInterval(()=>setTime(v=>v-1),1000);return()=>clearInterval(timer)},[screen,round]);
 useEffect(()=>{if(screen!=='game'||time>0)return;if(round===3){if(!bossDefeated&&risk==='risk')setGame(g=>({...g,score:Math.max(0,g.score-stake)}));progress(bossDefeated?'boss_defeated':'boss_escaped',{screen:'results'});setScreen(bossDefeated?'chest':'lost');return}setDraft(draftOptions(round));setScreen('draft');progress('reward_draft',{screen:'draft'})},[time,screen,round,bossDefeated,risk,stake]);
 function hit(t){setGame(g=>({...g,shots:g.shots+1}));if(t.type==='bomb'&&activeMods.shield){setActiveMods(m=>({...m,shield:false}));setTargets(x=>x.filter(y=>y.id!==t.id));return}if(t.type==='broken'&&t.hp>1){setTargets(x=>x.map(y=>y.id===t.id?{...y,hp:1}:y));setGame(g=>({...g,score:g.score+60*(activeMods.double?2:1),hits:g.hits+1,combo:g.combo+1,best:Math.max(g.best,g.combo+1)}));return}if(t.type==='cupid'){const hp=bossHp-1;setBossHp(hp);setTargets([]);setGame(g=>{const combo=g.combo+1,gain=(280+(8-hp)*35)*(activeMods.double?2:1);return{...g,score:g.score+gain,hits:g.hits+1,combo,best:Math.max(g.best,combo)}});if(hp<=0){setBossDefeated(true);if(risk==='risk')setGame(g=>({...g,score:g.score+stake*2}));setTimeout(()=>setScreen('chest'),450)}return}setTargets(x=>x.filter(y=>y.id!==t.id));setGame(g=>{const combo=(t.type==='bomb'||t.type==='decoy')?0:g.combo+1,m=1+Math.min(1.5,Math.floor(combo/4)*.25),gain=(t.type==='bomb'||t.type==='decoy')?POINTS[t.type]:Math.round(POINTS[t.type]*m*(activeMods.double?2:1));return{...g,score:Math.max(0,g.score+gain),hits:g.hits+((t.type==='bomb'||t.type==='decoy')?0:1),combo,best:Math.max(g.best,combo)}})}
 function chooseReward(item){setLoot(x=>[...x,item]);if(item.type==='power')setMods(m=>({...m,[item.id]:m[item.id]+1}));else{const next={...profile,collection:{...profile.collection,[item.id]:(profile.collection[item.id]||0)+1}};setProfile(next);saveProfile(next);setDiscounts(d=>({...d,[item.id]:.5}))}if(round===2){setStake(Math.floor(game.score*.25));setScreen('risk');progress('risk_decision',{screen:'risk'})}else beginRound(round+1)}
 function chooseRisk(choice){setRisk(choice);if(choice==='risk')setGame(g=>({...g,score:Math.max(0,g.score-stake)}));beginRound(3)}
 function cardCost(card){return Math.max(0,Math.round(card.cost*(discounts[card.id]||1)))}
 function toggle(card){const exists=plans[night].some(x=>x.id===card.id);if(exists){setPlans(p=>p.map((list,i)=>i===night?list.filter(x=>x.id!==card.id):list));return}const finalCost=cardCost(card);if(finalCost<=left&&finalCost<=wallet)setPlans(p=>p.map((list,i)=>i===night?[...list,{...card,finalCost}]:list))}
 function addCustom(){if(!custom.name.trim()||left<=0)return;const card={...custom,id:'custom-'+Date.now(),category:'Custom',rarity:'Forged',cost:left,finalCost:left,traits:{romance:3,fun:3,connection:3}};const next={...profile,custom:[...profile.custom,card]};setProfile(next);saveProfile(next);setPlans(p=>p.map((list,i)=>i===night?[...list,card]:list));setShowCustom(false)}
 async function finish(){const rewards=plans.slice(0,form.nights).flatMap((list,n)=>list.map(x=>({...x,night:n,points:x.finalCost})));const payload={sessionId,...form,...game,accuracy:Number(accuracy.toFixed(3)),rank,bossDefeated,risk,loot,rewards,code:code(),createdAt:new Date().toISOString()};const r=await fetch('/api/save-game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)return alert('Cupid could not save the date. Please try again.');const x=await r.json(),origin=location.origin;setSaved(payload);setLinks({mine:origin+'/review/'+x.creatorReviewToken,partnerReview:origin+'/review/'+x.partnerReviewToken,invite:origin+'/invite/'+x.inviteToken,itinerary:origin+'/redeem/'+x.code});setScreen('finale')}
 if(screen==='setup')return <Setup form={form} setForm={setForm} start={start}/>;
 if(screen==='game')return <main className="cv5-screen cv5-game"><City/><Sound/><Map round={round} screen={screen}/><header className="cv5-hud"><div><p className="cv5-kicker">{MAP[round].icon} {MAP[round].name}</p><b>{game.score.toLocaleString()}</b><small>{Math.max(0,goal-game.score)} to date vault</small></div><div className="cv5-timer">{time}</div></header>{round===3&&<div className="cv5-bossbar"><span>Cupid</span><i style={{width:(bossHp/8*100)+'%'}}/><b>{bossHp}/8</b></div>}<section className="cv5-arena" onClick={()=>setGame(g=>({...g,shots:g.shots+1,combo:0}))}>{targets.map(t=><button key={t.id} className={`cv5-target ${t.type} phase-${t.phase||1}`} style={{left:t.x+'%',top:t.y+'%'}} onClick={e=>{e.stopPropagation();hit(t)}}><span>{ICON[t.type]}</span>{t.hp>1&&<small>{t.hp}</small>}</button>)}</section><footer className="cv5-game-footer"><b>{game.combo}×<span>Combo</span></b><p>{activeMods.double?'✨ Double Love · ':''}{activeMods.shield?'🛡️ Shield · ':''}{MAP[round].help}</p><b>{game.best}×<span>Best</span></b></footer></main>;
 if(screen==='draft')return <main className="cv5-screen cv5-draft"><City/><Map round={round} screen={screen}/><section className="cv5-glass"><p className="cv5-kicker">Stage cleared</p><h1>Choose one reward</h1><div className="cv5-draft-grid">{draft.map((item,i)=><button key={item.id+i} className={rarityClass(item.rarity)} onClick={()=>chooseReward(item)}><span>{item.emoji}</span><small>{item.rarity} {item.type==='card'?'Date Card':'Power-Up'}</small><b>{item.name}</b><p>{item.text}</p></button>)}</div></section></main>;
 if(screen==='risk')return <main className="cv5-screen cv5-risk"><City/><Map round={3} screen="risk"/><section className="cv5-glass"><p className="cv5-kicker">Cupid's Tower</p><h1>Bank it—or risk it?</h1><p>You have {game.score.toLocaleString()} Love Points. Risk {stake.toLocaleString()} for a 2× boss payout.</p><div className="cv5-risk-actions"><button onClick={()=>chooseRisk('bank')}>🏦 Bank My Points<small>Keep everything. Standard boss rewards.</small></button><button className="danger" onClick={()=>chooseRisk('risk')}>🔥 Risk {stake.toLocaleString()}<small>Defeat Cupid and win {stake*2} bonus. Lose it if he escapes.</small></button></div></section></main>;
 if(screen==='lost')return <main className="cv5-screen cv5-state"><City/><section className="cv5-glass"><div className="cv5-big">💘</div><p className="cv5-kicker">Cupid escaped</p><h1>Run over.</h1><p>{game.score.toLocaleString()} points · {rank} Rank</p><button onClick={start}>Try Another Run</button></section></main>;
 if(screen==='chest'){const r=rankRun(game.score,goal,accuracy,game.best,bossDefeated);return <main className="cv5-screen cv5-state"><City/><section className="cv5-glass"><p className="cv5-kicker">Cupid defeated</p><div className={`cv5-rank rank-${r}`}>{r}</div><h1>{game.score.toLocaleString()} Love Points</h1><div className="cv5-run-stats"><b>{Math.round(accuracy*100)}%<span>Accuracy</span></b><b>{game.best}×<span>Best combo</span></b><b>{loot.length}<span>Loot</span></b></div><button className="cv5-chest" onClick={()=>setScreen('builder')}>🎁 <span>Open Date Vault</span></button></section></main>}
 if(screen==='builder')return <main className="cv5-builder"><Sound/><header className="cv5-wallet"><div><span>Love Points</span><b>{wallet.toLocaleString()}</b></div><div><span>Night {night+1} left</span><b>{left}</b></div><div><span>Run Rank</span><b>{rank}</b></div></header><section className="cv5-builder-title"><p className="cv5-kicker">Spend your ranked loot</p><h1>Build Night {night+1}</h1></section><nav className="cv5-night-nav">{Array.from({length:form.nights},(_,i)=>{const used=plans[i].reduce((n,x)=>n+x.finalCost,0);return <button key={i} disabled={i>night} className={i===night?'active':''} onClick={()=>setNight(i)}>Night {i+1}<small>{used}/{BUDGET}</small></button>})}</nav><section className="cv5-builder-grid"><aside className="cv5-cart"><h2>Tonight's Deck</h2><div className="cv5-meter"><i style={{width:Math.min(100,spent/BUDGET*100)+'%'}}/></div>{plans[night].map((x,i)=><article key={x.id} className={rarityClass(x.rarity)}><span>{x.emoji}</span><div><b>{x.name}</b><small>{x.rarity} · {x.finalCost} pts</small></div><button onClick={()=>toggle(x)}>×</button></article>)}{left>0&&<div className="cv5-gap"><b>{left} points remain</b><button onClick={()=>setShowCustom(true)}>Forge an exact-fit card</button></div>}{left===0&&(night<form.nights-1?<button className="cv5-continue" onClick={()=>setNight(n=>n+1)}>Lock Night {night+1} · Build Night {night+2}</button>:<button className="cv5-continue" onClick={finish}>Save & Invite My Date</button>)}</aside><section className="cv5-card-shop"><h2>Collectible Date Cards</h2><div>{allCards.map(card=>{const owned=profile.collection?.[card.id]||0,cost=cardCost(card),picked=plans[night].some(x=>x.id===card.id);return <button key={card.id} className={`${rarityClass(card.rarity)} ${picked?'picked':''}`} disabled={!picked&&(cost>left||cost>wallet)} onClick={()=>toggle(card)}><span>{card.emoji}</span><small>{card.rarity}{owned?` · Owned ${owned}`:''}</small><b>{card.name}</b><p>{card.category} · {card.duration}</p><em>{discounts[card.id]?`${cost} pts · Loot discount`:`${cost} pts`}</em></button>})}</div></section></section>{showCustom&&<div className="cv5-modal"><section><h2>Forge Your Own Date Card</h2><input value={custom.name} onChange={e=>setCustom({...custom,name:e.target.value})} placeholder="Activity name"/><div><input value={custom.emoji} onChange={e=>setCustom({...custom,emoji:e.target.value})} placeholder="Emoji"/><input value={custom.duration} onChange={e=>setCustom({...custom,duration:e.target.value})} placeholder="Duration"/></div><textarea value={custom.notes} onChange={e=>setCustom({...custom,notes:e.target.value})} placeholder="Location, notes, what to bring..."/><p>This forged card costs exactly <b>{left} points</b>.</p><button onClick={addCustom}>Add Forged Card</button><button className="ghost" onClick={()=>setShowCustom(false)}>Cancel</button></section></div>}</main>;
 if(screen==='finale'&&saved&&links)return <main className="cv5-screen cv5-finale"><City/><section className="cv5-glass"><p className="cv5-kicker">Date saved · invitation ready</p><div className={`cv5-rank rank-${saved.rank}`}>{saved.rank}</div><h1>{saved.playerName} & {saved.partnerName}</h1><b className="cv5-code">{saved.code}</b><div className="cv5-share-stack"><button onClick={()=>shareNative('Cupid built us a date',`${saved.partnerName}, Cupid built this date for us. Tap to see it and let me know you're in.`,links.invite)}>💌 Share Date Invitation</button><button onClick={()=>location.href=links.mine}>⭐ Rate My Experience</button><button onClick={()=>shareNative('Your private Cupid review',`${saved.partnerName}, rate our date privately. Our shared result unlocks after we both answer.`,links.partnerReview)}>🔐 Share Partner Review</button><button className="ghost" onClick={()=>location.href=links.itinerary}>Open Itinerary</button></div><p className="cv5-fine">The invitation lets your partner tap “I'm In.” The private review link is separate and should be sent after the date.</p></section></main>;
 return null;
}
